# Generated by Django 4.2.2 on 2023-06-25 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nproduct", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Nproduct",
        ),
    ]
